"""empty message

Revision ID: d6216ffe0c04
Revises: 
Create Date: 2022-10-06 10:50:14.070327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6216ffe0c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=50), nullable=False),
    sa.Column('admin_email', sa.String(length=20), nullable=True),
    sa.Column('admin_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('emp_id'),
    sa.UniqueConstraint('admin_email'),
    sa.UniqueConstraint('admin_password')
    )
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medi_name', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('rate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medi_name')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('phone_no', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=5), nullable=True),
    sa.Column('bed_type', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('medicine')
    op.drop_table('admin')
    # ### end Alembic commands ###
